Add test on compatibility

diff --git a/.github/workflows/test-extensions.yml b/.github/workflows/test-extensions.yml
--- a/.github/workflows/test-extensions.yml
+++ b/.github/workflows/test-extensions.yml
@@ -15,6 +15,37 @@ defaults:
     shell: bash
 
 jobs:
+  labextension-compatibility:
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 10
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-22.04]
+    steps:
+      - uses: actions/checkout@v3
+      - name: Install node
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18.x'
+      # NOTE: actions/setup-python@v2 can make use of a cache within the GitHub
+      #       Action virtual environment and setup extremely fast. 3.9 isn't
+      #       available in this cache as of November 2020.
+      - name: Install Python ${{ matrix.python }}
+        uses: actions/setup-python@v2
+      - name: Install package
+        run: |
+          python -m pip install --upgrade pip wheel setuptools
+          pip install -e .
+          pip freeze
+      - name: Check compatibility
+        run: |
+          if [[ $(jupyter labextension list 2>&1 | grep ' X') ]]
+          then
+            echo "Compatibility error"
+            jupyter labextension list
+            exit 1
+          fi
+
   ui-test:
     runs-on: ${{ matrix.os }}
     timeout-minutes: 40
